### ISSUE TITLE
Import Fails with SCSS nesting

### ISSUE THREAD

**Issue by stolinski** [yuanchuan/vite-plugin-autoimport#17]
Still working on a reproduction of this one, but I found an interesting issue. 

Using a auto imported `<Button>` I found that a line in my css causes the build to fail.

```
.search-button {
  margin-top: 0.5rem;
  padding-right: 1rem;
}
```

So straight up deleting that search button css would fix this issue.

**Comment by stolinski** [comment]
Now I'm seeing this with any nested scss, so it may not be the class name as suspected, but something with nesting scss. Def something weird in the <style> tag though. Component renders fine without the auto-imported one.

**Comment by stolinski** [comment]
Ok, reproduction here. https://stackblitz.com/edit/sveltejs-kit-template-default-v1u2z1?file=src/lib/Counter.svelte

Seems like if there is nested css using lang scss, it breaks. 
See Counter.svelte. I've trimmed it down to the essentials here, but if you comment out nested span here:
```
	.nested {
		span {
			color: red;
		}
	}
```
It works again.

Edit:
I've found that 
```
index.js 
        if (preprocess && preprocess.length) {
          let result = await svelte.preprocess(code, preprocess);
          code = result.code;
        }
```
Is def the cause. I'm not sure if it's the preprocess part that's breaking or something in the transformCode() function, but it does seem like running svelte.preprocess() isn't correctly preprocessing.

Edit 2: Seems like it's not correctly identifying my scss for some reason in the svelte.preprocess from within this package. It's finding the correct svelte.config.js file, but failes when running with this error in the try/catch

```
CompileError [ParseError]: Identifier is expected
    at error (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:17714:19)
    at Parser$1.error (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:17790:9)
    at Object.read_style [as read] (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:14465:20)
    at tag (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:16838:33)
    at new Parser$1 (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:17749:21)
    at Module.parse$3 (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/svelte@3.47.0/node_modules/svelte/compiler.mjs:17881:20)
    at TransformContext.transform (file:///Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/sveltekit-autoimport@1.6.5/node_modules/sveltekit-autoimport/src/index.js:126:22)
    at Object.transform (/Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/vite@2.9.5_sass@1.50.1/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:36672:53)
    at doTransform (/Users/scotttolinski/Sites/Level-Up-Tutorials/node_modules/.pnpm/vite@2.9.5_sass@1.50.1/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:55662:51) {
  code: 'css-syntax-error',
  start: { line: 174, column: 2, character: 4702 },
  end: { line: 174, column: 2, character: 4702 },
  pos: 4702,
  filename: undefined,
  frame: '172: \n' +
    '173:   .div {\n' +
    '174:     .yo {\n' +
    '         ^\n' +
    '175:       display: none;\n' +
    '176:     }'
}
```

**Comment by yuanchuan** [comment]
Should be fixed now in `1.6.6`

**Comment by stolinski** [comment]
You are amazing.

**Comment by Heliodex** [comment]
Seems to error similarly for styling with the indented Sass format: [basic repro](https://github.com/Heliodex/sveltekit-autoimport-sass-repro)
edit: fixed repo being private

**Comment by Heliodex** [comment]
> Seems to error similarly for styling with the indented Sass format: [basic repro](https://github.com/Heliodex/sveltekit-autoimport-sass-repro) edit: fixed repo being private

Nevermind, this appears to be an issue with the incorrect order I put the preprocessors in
